### ISSUE TITLE
C error: Expected 2 fields in line 91, saw 3

### ISSUE THREAD

**Issue by Hongcheng-Gao** [UKPLab/naacl2019-like-humans-visual-attacks#17]
When I run VIPER(p,DCES),  there is a error"pandas.errors.ParserError: Error tokenizing data. C error: Expected 2 fields in line 91, saw 3"

**Comment by SteffenEger** [comment]
Could you provide more context? When I run "python3 viper_dces.py -p 0.4 -d sample.txt", it works.

**Comment by Hongcheng-Gao** [comment]
![image](https://user-images.githubusercontent.com/96536860/171289319-f695dcaf-480c-4878-9905-c4067716ba8b.png)
I think there are some bad lines which cannot be splited by '\t'. There are lines which has been splited to more  than 2 colums by pandas.

**Comment by SteffenEger** [comment]
Runs without any problems on my linux machine. Maybe you have a different machine or a different version (of pandas). 
If things don't work for you, you can also try to read NamesList.txt without pandas.

**Comment by Hongcheng-Gao** [comment]
I see. Thank you!

**Comment by Hongcheng-Gao** [comment]
btw, could you tell the version of your pandas?

**Comment by SteffenEger** [comment]
That's what I get:

>>> pd.__version__
'0.23.4'

**Comment by Hongcheng-Gao** [comment]
OK， thanks!
