### ISSUE TITLE
how to get the file "vce.normalized"

### ISSUE THREAD

**Issue by goCurrent** [UKPLab/naacl2019-like-humans-visual-attacks#5]
from the file 'mydraw_individual.py' I can see how to draw a char, the pixels are up to 255, but in the file 'vce.normalized'  most of them are smaller than 1, how to get process the ppm files? thanks

**Comment by SteffenEger** [comment]
Good point. We normalized them. For the embedding file, we substracted the column-wise means and normalized them to unit length, I believe. Column-wise mean: take the matrix of characters times embedding dimensions and from each dimension subtract the mean of the whole column.

**Comment by goCurrent** [comment]
sorry I don't quite understand. Here is my understanding: 
(1)Column-wise mean: In the paper dim is 576: E[0,1,...575], for each char,  E[i] subtract the mean of all char's E[i].
(2) normalize: column-wise normalization? between(-10,10) ? I don't know what the 'unit length' mean.
And I feel puzzled with the pixels: In the  'mydraw_individual.py'  it's in 'RGB'mode, 3 channels, how to transfer to a single one, add all the three channels?

**Comment by SteffenEger** [comment]
Yes, say you have 1000 characters, each being D dimensional. Then, you have a matrix of size 1000 x D. From this we subtracted the column-wise mean (each column is a vector and has a mean). Then we normalized each row to have unit length. At least, that's what I assume we did. I don't remember the exact details.
For the RGB code: hm, yeah, I also don't remember what we did there. Three colors doesn't make sense. And it should definitely save it in some form of text format. Maybe we did some ppm2ascii or something. If I find the old source code, I'll let you know.

**Comment by goCurrent** [comment]
OK, I get it, thanks a lot.  The normalization operation is just easily cutting D dim to unit length or dimension reduction or the original D is the wanted length? Thanks again for your reply.

**Comment by SteffenEger** [comment]
We're not doing dimensionality reduction. D stays at 576. Actually, you could check in the vce.embedding file. D should be 576 and it should be unit length (np.linalg.norm)

**Comment by goCurrent** [comment]
thanks👍

**Comment by SteffenEger** [comment]
For the ppm, you can do 

> pnmnoraw my.ppm

on Linux to get a text file. The three colors (RGB) will be identical, so just keep one of them.

**Comment by goCurrent** [comment]
👌Get it, thanks
