### ISSUE TITLE
embeddings_velmo.py missing

### ISSUE THREAD

**Issue by k4d3v** [UKPLab/naacl2019-like-humans-visual-attacks#6]
It looks like the file embeddings_velmo.py is missing in code/sanity_check/sanity_check.py, as I get ModuleNotFoundError: No module named 'embeddings_velmo'  in line 14 when I try to execute the script sanity_check.py. I am using python 3.6 venv.
Thanks in advance for your help!

**Comment by SteffenEger** [comment]
This part of the code was written by one of the co-authors who is unavailable at the moment unfortunately (the code was part of the appendix anyway). 
Maybe you can try if you find something helpful here: 
 https://github.com/UKPLab/naacl2019-like-humans-visual-attacks/tree/master/code/POS_Chunk

**Comment by SteffenEger** [comment]
We seemingly found it again and added it.
